import React from 'react';
import { Link } from 'react-scroll';  // Import Link from react-scroll

function Footer() {
  return (
    <div className="bg-black text-white h-screen flex flex-col justify-between">

      <div className="flex flex-row justify-between items-center w-full h-full px-16">
        <div className="space-y-8">
          <h1 className="text-6xl font-bold">
            Don't Miss Our <br /> Internship Program
          </h1>
          <p className="text-2xl">
            Apply now for hands-on experience in cybersecurity with <br />
            our exclusive 6-month internship program.
          </p>
        </div>

        {/* Use Link component for smooth scroll to Contact Us */}
        <div>
          <Link to="contactus" smooth={true} duration={500}>
            <button className="bg-purple-700 text-white px-12 py-6 rounded-full text-2xl font-semibold hover:bg-purple-800 transition duration-300">
              Apply Now
            </button>
          </Link>
        </div>
      </div>

      <footer className="bg-black py-4">
        <div className="border-t border-gray-600 mx-6"></div>
        <div className="flex justify-between items-center text-gray-400 mt-2 px-6">
          <p className="text-sm">© 2024 SecuredCodeHub. All rights reserved.</p>
          <div className="flex items-center">
            <p className="text-sm">Generated by securedcodehub</p>
          </div>
        </div>
      </footer>

    </div>
  );
}

export default Footer;
